package com.orderservice.util;

public class Constants {
	public static final String INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK";
	public static final String DRAFT_ORDER_CREATED_SUCCESSFULLLY = "DRAFT_ORDER_CREATED_SUCCESSFULLLY";
	public static final String IST = "Asia/Kolkata";
    public static final String UNKNOWN_EXCEPTION_OCCURRED = "UNKNOWN_EXCEPTION_OCCURRED";
    public static final String ORDER_UPDATED_SUCCESSFULLY = "ORDER_UPDATED_SUCCESSFULLY";
    public static final String ORDER_NOT_FOUND = "ORDER_NOT_FOUND";
    public static final String ORDER_CANCELLED_SUCCESSFULLY = "ORDER_CANCELLED_SUCCESSFULLY";
    public static final String ORDERITEMS_CANCELLED_SUCCESSFULLY = "ORDERITEMS_CANCELLED_SUCCESSFULLY";
    public static final String RETURN_REQUEST_INITIATED_SUCCESSFULLY = "RETURN_REQUEST_INITIATED_SUCCESSFULLY";
    public static final String REPLACEMENT_REQUEST_INITIATED_SUCCESSFULLY = "REPLACEMENT_REQUEST_INITIATED_SUCCESSFULLY";
    public static final String ORDER_PLACED_SUCCESSFULLY = "ORDER_PLACED_SUCCESSFULLY";
}
