package com.orderservice.entity;

public enum ConsignmentStatusEnum {
	NO_STATUS,
	CREATED,
	PACKED,
	LOGISTICS_PICKED,
	LOGISTICS_DELIVERED,
	PICKED_UP,
	OUT_FOR_DELIVERY,
	OUT_FOR_PICKUP,
	COMPLETED,
	PARTIALLY_CANCELLED,
	CANCELLED,
	USER_CANCELLED,
	BUSINESS_CANCELLED
}
