package com.notificationservice.entity;

public enum EmailTypeEnum {
	VERIFY_OTP,
	SHIPPED,
	OUT_FOR_DELIVERY,
	DELIVERED,
	OUT_FOR_PICKUP,
	PICKED_UP,
	ORDER_CONFIRMATION,
	ORDER_CANCELLATION,
	RETURN_REQUEST_RAISED,
	REPLACEMENT_REQUEST_RAISED,
	PICKUP_REQUEST_CANCELLED
}
