package com.consignmentservice.util;

public class Constants {
	public static final String IST = "Asia/Kolkata";
    public static final String UNKNOWN_EXCEPTION_OCCURRED = "UNKNOWN_EXCEPTION_OCCURRED";
    public static final String CONSIGNMENT_CREATED_SUCCESSFULLY = "CONSIGNMENT_CREATED_SUCCESSFULLY";
    public static final String CONSIGNMENT_UPDATED_SUCCESSFULLY = "CONSIGNMENT_UPDATED_SUCCESSFULLY";
    public static final String CONSIGNMENT_CANCELLED_SUCCESSFULLY = "CONSIGNMENT_CANCELLED_SUCCESSFULLY";
    public static final String CONSIGNMENTITEMS_CANCELLED_SUCCESSFULLY = "CONSIGNMENTITEMS_CANCELLED_SUCCESSFULLY";
    public static final String TRANSACTION_CREATED_SUCCESSFULLY = "TRANSACTION_CREATED_SUCCESSFULLY";
    public static final String INVALID_CONSIGNMENT_NUMBER = "INVALID_CONSIGNMENT_NUMBER";
}
