package com.inventoryservice.util;

public class Constants {

		public static final String IST = "Asia/Kolkata";
	    public static final String UNKNOWN_EXCEPTION_OCCURRED = "UNKNOWN_EXCEPTION_OCCURRED";

	    public static final String LOGISTICS_FETCHED_SUCCESSFULLY = "LOGISTICS_FETCHED_SUCCESSFULLY";
	    public static final String LOGISTICS_NOT_FOUND = "LOGISTICS_NOT_FOUND";
	    public static final String LOGISTICS_CREATED_SUCCESSFULLY = "LOGISTICS_CREATED_SUCCESSFULLY";
	    public static final String LOGISTICS_ALREADY_FOUND = "LOGISTICS_ALREADY_FOUND";
	    public static final String LOGISTICS_UPDATED_SUCCESSFULLY = "LOGISTICS_UPDATED_SUCCESSFULLY";

	    public static final String PINCODE_FETCHED_SUCCESSFULLY = "PINCODE_FETCHED_SUCCESSFULLY";
	    public static final String PINCODE_NOT_FOUND = "PINCODE_NOT_FOUND";
	    public static final String PINCODE_CREATED_SUCCESSFULLY = "PINCODE_CREATED_SUCCESSFULLY";
	    public static final String PINCODE_ALREADY_FOUND = "PINCODE_ALREADY_FOUND";
	    public static final String PINCODE_UPDATED_SUCCESSFULLY = "PINCODE_UPDATED_SUCCESSFULLY";

	    public static final String STATE_FETCHED_SUCCESSFULLY = "STATE_FETCHED_SUCCESSFULLY";
	    public static final String STATE_NOT_FOUND = "STATE_NOT_FOUND";
	    public static final String STATE_CREATED_SUCCESSFULLY = "STATE_CREATED_SUCCESSFULLY";
	    public static final String STATE_ALREADY_FOUND = "STATE_ALREADY_FOUND";
	    public static final String STATE_UPDATED_SUCCESSFULLY = "STATE_UPDATED_SUCCESSFULLY";

	    public static final String STOCK_FETCHED_SUCCESSFULLY = "STOCK_FETCHED_SUCCESSFULLY";
	    public static final String STOCK_NOT_FOUND = "STOCK_NOT_FOUND";
	    public static final String STOCK_CREATED_SUCCESSFULLY = "STOCK_CREATED_SUCCESSFULLY";
	    public static final String STOCK_ALREADY_FOUND = "STOCK_ALREADY_FOUND";
	    public static final String STOCK_UPDATED_SUCCESSFULLY = "STOCK_UPDATED_SUCCESSFULLY";
	    public static final String STOCKCOUNT_CANNOT_BE_ZERO_OR_NEGATIVE = "STOCKCOUNT_CANNOT_BE_ZERO_OR_NEGATIVE";

	    public static final String WAREHOUSE_FETCHED_SUCCESSFULLY = "WAREHOUSE_FETCHED_SUCCESSFULLY";
	    public static final String WAREHOUSE_NOT_FOUND = "WAREHOUSE_NOT_FOUND";
	    public static final String WAREHOUSE_CREATED_SUCCESSFULLY = "WAREHOUSE_CREATED_SUCCESSFULLY";
	    public static final String WAREHOUSE_ALREADY_FOUND = "WAREHOUSE_ALREADY_FOUND";
	    public static final String WAREHOUSE_UPDATED_SUCCESSFULLY = "WAREHOUSE_UPDATED_SUCCESSFULLY";

	    public static final String STOCK_MOVEMENT_FETCHED_SUCCESSFULLY = "STOCK_MOVEMENT_FETCHED_SUCCESSFULLY";
	    public static final String STOCK_MOVEMENT_NOT_FOUND = "STOCK_MOVEMENT_NOT_FOUND";
	    public static final String STOCK_MOVEMENT_CREATED_SUCCESSFULLY = "STOCK_MOVEMENT_CREATED_SUCCESSFULLY";
	    public static final String STOCK_MOVEMENT_ALREADY_FOUND = "STOCK_MOVEMENT_ALREADY_FOUND";
	    public static final String STOCK_MOVEMENT_UPDATED_SUCCESSFULLY = "STOCK_MOVEMENT_UPDATED_SUCCESSFULLY";

	
}
