package com.userservice.util;

public class Constants {
	public static final String CUSTOMER_CREATED_SUCCESSFULLY = "CUSTOMER_CREATED_SUCCESSFULLY";
	public static final String CUSTOMER_UPDATED_SUCCESSFULLY = "CUSTOMER_UPDATED_SUCCESSFULLY";
	public static final String CUSTOMER_FETCHED_SUCCESSFULLY = "CUSTOMER_FETCHED_SUCCESSFULLY";
	public static final String CUSTOMER_ALREADY_FOUND = "CUSTOMER_ALREADY_FOUND";
	public static final String ROLE_CREATED_SUCCESSFULLY = "ROLE_CREATED_SUCCESSFULLY";
	public static final String ROLE_UPDATED_SUCCESSFULLY = "ROLE_UPDATED_SUCCESSFULLY";
	public static final String ROLE_FETCHED_SUCCESSFULLY = "ROLE_FETCHED_SUCCESSFULLY";
	public static final String ROLE_ALREADY_FOUND = "ROLE_ALREADY_FOUND";
	public static final String DEPARTMENT_CREATED_SUCCESSFULLY = "DEPARTMENT_CREATED_SUCCESSFULLY";
	public static final String DEPARTMENT_UPDATED_SUCCESSFULLY = "DEPARTMENT_UPDATED_SUCCESSFULLY";
	public static final String DEPARTMENT_FETCHED_SUCCESSFULLY = "DEPARTMENT_FETCHED_SUCCESSFULLY";
	public static final String DEPARTMENT_ALREADY_FOUND = "DEPARTMENT_ALREADY_FOUND";
	public static final String EMPLOYEE_CREATED_SUCCESSFULLY = "EMPLOYEE_CREATED_SUCCESSFULLY";
	public static final String EMPLOYEE_UPDATED_SUCCESSFULLY = "EMPLOYEE_UPDATED_SUCCESSFULLY";
	public static final String EMPLOYEE_FETCHED_SUCCESSFULLY = "EMPLOYEE_FETCHED_SUCCESSFULLY";
	public static final String EMPLOYEE_ALREADY_FOUND = "EMPLOYEE_ALREADY_FOUND";
	public static final String CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND";
	public static final String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
	public static final String DEPARTMENT_NOT_FOUND = "DEPARTMENT_NOT_FOUND";
	public static final String EMPLOYEE_NOT_FOUND = "EMPLOYEE_NOT_FOUND";
	public static final String IST = "Asia/Kolkata";
	public static final String UNKNOWN_EXCEPTION_OCCURRED = "UNKNOWN_EXCEPTION_OCCURRED";
}
